/** 数据库类型目录：值严格对齐 dbx 引擎 DatabaseType 的序列化名。 */

export type DatabaseTypeGroup = "relational" | "nosql" | "cloud" | "search" | "timeseries" | "kv" | "other";

export type DatabaseTypeGroupLabelKey =
	| "databaseTypeGroup.relational"
	| "databaseTypeGroup.nosql"
	| "databaseTypeGroup.cloud"
	| "databaseTypeGroup.search"
	| "databaseTypeGroup.timeseries"
	| "databaseTypeGroup.kv"
	| "databaseTypeGroup.other";

export interface DatabaseTypeMeta {
	readonly value: string;
	readonly label: string;
	readonly badge: string;
	readonly color: string;
	readonly group: DatabaseTypeGroup;
	readonly defaultPort: string;
	readonly hostPlaceholder: string;
	/** host 字段表示本地文件路径（SQLite / DuckDB 等）。 */
	readonly fileBased?: boolean;
}

export const DATABASE_TYPE_GROUPS: readonly { id: DatabaseTypeGroup; labelKey: DatabaseTypeGroupLabelKey }[] = [
	{ id: "relational", labelKey: "databaseTypeGroup.relational" },
	{ id: "nosql", labelKey: "databaseTypeGroup.nosql" },
	{ id: "cloud", labelKey: "databaseTypeGroup.cloud" },
	{ id: "search", labelKey: "databaseTypeGroup.search" },
	{ id: "timeseries", labelKey: "databaseTypeGroup.timeseries" },
	{ id: "kv", labelKey: "databaseTypeGroup.kv" },
	{ id: "other", labelKey: "databaseTypeGroup.other" },
];

const t = <T>(value: T): T => value;

export const DATABASE_TYPES: readonly DatabaseTypeMeta[] = t([
	// 关系型 / OLAP
	{
		value: "sqlite",
		label: "SQLite",
		badge: "SQ",
		color: "#38bdf8",
		group: "relational",
		defaultPort: "",
		hostPlaceholder: "C:/path/to/database.db",
		fileBased: true,
	},
	{
		value: "postgres",
		label: "PostgreSQL",
		badge: "PG",
		color: "#336791",
		group: "relational",
		defaultPort: "5432",
		hostPlaceholder: "localhost",
	},
	{
		value: "mysql",
		label: "MySQL",
		badge: "MY",
		color: "#00758f",
		group: "relational",
		defaultPort: "3306",
		hostPlaceholder: "localhost",
	},
	{
		value: "sqlserver",
		label: "SQL Server",
		badge: "MS",
		color: "#cc2927",
		group: "relational",
		defaultPort: "1433",
		hostPlaceholder: "localhost",
	},
	{
		value: "oracle",
		label: "Oracle",
		badge: "OR",
		color: "#f80000",
		group: "relational",
		defaultPort: "1521",
		hostPlaceholder: "localhost",
	},
	{
		value: "duckdb",
		label: "DuckDB",
		badge: "DU",
		color: "#fff000",
		group: "relational",
		defaultPort: "",
		hostPlaceholder: "path/to/data.duckdb 或 :memory:",
		fileBased: true,
	},
	{
		value: "clickhouse",
		label: "ClickHouse",
		badge: "CH",
		color: "#ffcc01",
		group: "relational",
		defaultPort: "8123",
		hostPlaceholder: "localhost",
	},
	{
		value: "doris",
		label: "Apache Doris",
		badge: "DO",
		color: "#3b5bdb",
		group: "relational",
		defaultPort: "9030",
		hostPlaceholder: "localhost",
	},
	{
		value: "starrocks",
		label: "StarRocks",
		badge: "SR",
		color: "#3b5bdb",
		group: "relational",
		defaultPort: "9030",
		hostPlaceholder: "localhost",
	},
	{
		value: "opengauss",
		label: "openGauss",
		badge: "OG",
		color: "#5b8def",
		group: "relational",
		defaultPort: "5432",
		hostPlaceholder: "localhost",
	},
	{
		value: "oceanbase-oracle",
		label: "OceanBase (Oracle)",
		badge: "OB",
		color: "#ff6a00",
		group: "relational",
		defaultPort: "2883",
		hostPlaceholder: "localhost",
	},
	{
		value: "h2",
		label: "H2",
		badge: "H2",
		color: "#00a3e0",
		group: "relational",
		defaultPort: "9092",
		hostPlaceholder: "localhost",
	},
	{
		value: "firebird",
		label: "Firebird",
		badge: "FB",
		color: "#e8423a",
		group: "relational",
		defaultPort: "3050",
		hostPlaceholder: "localhost",
	},
	{
		value: "access",
		label: "Microsoft Access",
		badge: "AC",
		color: "#a4373a",
		group: "relational",
		defaultPort: "",
		hostPlaceholder: "C:/path/to/database.accdb",
		fileBased: true,
	},
	{
		value: "gaussdb",
		label: "GaussDB",
		badge: "GS",
		color: "#c7000b",
		group: "relational",
		defaultPort: "5432",
		hostPlaceholder: "localhost",
	},
	{
		value: "dameng",
		label: "DM Database",
		badge: "DM",
		color: "#006b5f",
		group: "relational",
		defaultPort: "5236",
		hostPlaceholder: "localhost",
	},
	{
		value: "kingbase",
		label: "KingbaseES",
		badge: "KB",
		color: "#7b1fa2",
		group: "relational",
		defaultPort: "54321",
		hostPlaceholder: "localhost",
	},

	// NoSQL
	{
		value: "mongodb",
		label: "MongoDB",
		badge: "MO",
		color: "#47a248",
		group: "nosql",
		defaultPort: "27017",
		hostPlaceholder: "localhost",
	},
	{
		value: "redis",
		label: "Redis",
		badge: "RE",
		color: "#dc382d",
		group: "nosql",
		defaultPort: "6379",
		hostPlaceholder: "localhost",
	},
	{
		value: "cassandra",
		label: "Cassandra",
		badge: "CA",
		color: "#1287b1",
		group: "nosql",
		defaultPort: "9042",
		hostPlaceholder: "localhost",
	},
	{
		value: "neo4j",
		label: "Neo4j",
		badge: "N4",
		color: "#4581c3",
		group: "nosql",
		defaultPort: "7687",
		hostPlaceholder: "localhost",
	},
	{
		value: "hbase",
		label: "HBase",
		badge: "HB",
		color: "#990000",
		group: "nosql",
		defaultPort: "2181",
		hostPlaceholder: "localhost",
	},
	{
		value: "rqlite",
		label: "rqlite",
		badge: "RQ",
		color: "#2f855a",
		group: "nosql",
		defaultPort: "4001",
		hostPlaceholder: "localhost",
	},
	{
		value: "turso",
		label: "Turso",
		badge: "TU",
		color: "#4ff8d2",
		group: "nosql",
		defaultPort: "8080",
		hostPlaceholder: "localhost",
	},
	{
		value: "cloudflare-d1",
		label: "Cloudflare D1",
		badge: "D1",
		color: "#f6821f",
		group: "nosql",
		defaultPort: "443",
		hostPlaceholder: "account.d1.cloudflaredns.com",
	},

	// 云端数据仓库 / 分析引擎
	{
		value: "snowflake",
		label: "Snowflake",
		badge: "SF",
		color: "#29b5e8",
		group: "cloud",
		defaultPort: "443",
		hostPlaceholder: "account.snowflakecomputing.com",
	},
	{
		value: "bigquery",
		label: "BigQuery",
		badge: "BQ",
		color: "#4285f4",
		group: "cloud",
		defaultPort: "443",
		hostPlaceholder: "bigquery.googleapis.com",
	},
	{
		value: "redshift",
		label: "Amazon Redshift",
		badge: "RS",
		color: "#8b4da3",
		group: "cloud",
		defaultPort: "5439",
		hostPlaceholder: "cluster.region.redshift.amazonaws.com",
	},
	{
		value: "databricks",
		label: "Databricks",
		badge: "DBX",
		color: "#ff3621",
		group: "cloud",
		defaultPort: "443",
		hostPlaceholder: "workspace.cloud.databricks.com",
	},
	{
		value: "trino",
		label: "Trino",
		badge: "TR",
		color: "#dd00a1",
		group: "cloud",
		defaultPort: "8080",
		hostPlaceholder: "localhost",
	},
	{
		value: "prestosql",
		label: "Presto SQL",
		badge: "PS",
		color: "#48929b",
		group: "cloud",
		defaultPort: "8080",
		hostPlaceholder: "localhost",
	},
	{
		value: "hive",
		label: "Hive",
		badge: "HI",
		color: "#fdee00",
		group: "cloud",
		defaultPort: "10000",
		hostPlaceholder: "localhost",
	},
	{
		value: "spark",
		label: "Spark SQL",
		badge: "SP",
		color: "#e25a1c",
		group: "cloud",
		defaultPort: "10000",
		hostPlaceholder: "localhost",
	},
	{
		value: "db2",
		label: "IBM Db2",
		badge: "D2",
		color: "#054ada",
		group: "cloud",
		defaultPort: "50000",
		hostPlaceholder: "localhost",
	},
	{
		value: "saphana",
		label: "SAP HANA",
		badge: "SH",
		color: "#008fd3",
		group: "cloud",
		defaultPort: "30015",
		hostPlaceholder: "localhost",
	},
	{
		value: "teradata",
		label: "Teradata",
		badge: "TD",
		color: "#f37421",
		group: "cloud",
		defaultPort: "1025",
		hostPlaceholder: "localhost",
	},
	{
		value: "vertica",
		label: "Vertica",
		badge: "VE",
		color: "#2c3e50",
		group: "cloud",
		defaultPort: "5433",
		hostPlaceholder: "localhost",
	},
	{
		value: "databend",
		label: "Databend",
		badge: "DB",
		color: "#6c5ce7",
		group: "cloud",
		defaultPort: "8000",
		hostPlaceholder: "localhost",
	},

	// 搜索 / 向量
	{
		value: "elasticsearch",
		label: "Elasticsearch",
		badge: "ES",
		color: "#fec514",
		group: "search",
		defaultPort: "9200",
		hostPlaceholder: "localhost",
	},
	{
		value: "easysearch",
		label: "Easysearch",
		badge: "EY",
		color: "#fec514",
		group: "search",
		defaultPort: "9200",
		hostPlaceholder: "localhost",
	},
	{
		value: "meilisearch",
		label: "Meilisearch",
		badge: "ME",
		color: "#ff5caa",
		group: "search",
		defaultPort: "7700",
		hostPlaceholder: "localhost",
	},
	{
		value: "manticoresearch",
		label: "Manticore Search",
		badge: "MN",
		color: "#ff5a5f",
		group: "search",
		defaultPort: "9306",
		hostPlaceholder: "localhost",
	},
	{
		value: "qdrant",
		label: "Qdrant",
		badge: "QD",
		color: "#ea2845",
		group: "search",
		defaultPort: "6333",
		hostPlaceholder: "localhost",
	},
	{
		value: "milvus",
		label: "Milvus",
		badge: "MV",
		color: "#00a1ea",
		group: "search",
		defaultPort: "19530",
		hostPlaceholder: "localhost",
	},
	{
		value: "weaviate",
		label: "Weaviate",
		badge: "WV",
		color: "#49b16a",
		group: "search",
		defaultPort: "8080",
		hostPlaceholder: "localhost",
	},
	{
		value: "chromadb",
		label: "ChromaDB",
		badge: "CR",
		color: "#6c5ce7",
		group: "search",
		defaultPort: "8000",
		hostPlaceholder: "localhost",
	},

	// 时序
	{
		value: "influxdb",
		label: "InfluxDB",
		badge: "IN",
		color: "#22adf6",
		group: "timeseries",
		defaultPort: "8086",
		hostPlaceholder: "localhost",
	},
	{
		value: "questdb",
		label: "QuestDB",
		badge: "QD",
		color: "#d2181f",
		group: "timeseries",
		defaultPort: "9000",
		hostPlaceholder: "localhost",
	},
	{
		value: "victoriametrics",
		label: "VictoriaMetrics",
		badge: "VM",
		color: "#621773",
		group: "timeseries",
		defaultPort: "8428",
		hostPlaceholder: "localhost",
	},
	{
		value: "tdengine",
		label: "TDengine",
		badge: "TE",
		color: "#41b883",
		group: "timeseries",
		defaultPort: "6030",
		hostPlaceholder: "localhost",
	},
	{
		value: "iotdb",
		label: "IoTDB",
		badge: "IO",
		color: "#f58b33",
		group: "timeseries",
		defaultPort: "6667",
		hostPlaceholder: "localhost",
	},

	// 键值 / 协调
	{
		value: "etcd",
		label: "etcd",
		badge: "ET",
		color: "#419eda",
		group: "kv",
		defaultPort: "2379",
		hostPlaceholder: "localhost",
	},
	{
		value: "zookeeper",
		label: "ZooKeeper",
		badge: "ZK",
		color: "#8b5cf6",
		group: "kv",
		defaultPort: "2181",
		hostPlaceholder: "localhost",
	},
	{
		value: "nacos",
		label: "Nacos",
		badge: "NA",
		color: "#00b96b",
		group: "kv",
		defaultPort: "8848",
		hostPlaceholder: "localhost",
	},
	{
		value: "consul",
		label: "Consul",
		badge: "CO",
		color: "#f24c53",
		group: "kv",
		defaultPort: "8500",
		hostPlaceholder: "localhost",
	},
	{
		value: "mqtt",
		label: "MQTT",
		badge: "MQ",
		color: "#660066",
		group: "kv",
		defaultPort: "1883",
		hostPlaceholder: "localhost",
	},
	{
		value: "mq",
		label: "MQ Admin",
		badge: "MQ",
		color: "#d97706",
		group: "kv",
		defaultPort: "9092",
		hostPlaceholder: "localhost",
	},
]);

export const DATABASE_TYPE_META: Readonly<Record<string, DatabaseTypeMeta>> = Object.fromEntries(
	DATABASE_TYPES.map((meta) => [meta.value, meta]),
) as Record<string, DatabaseTypeMeta>;

export function getDatabaseTypeMeta(value: string): DatabaseTypeMeta {
	return (
		DATABASE_TYPE_META[value] ?? {
			value,
			label: "Database",
			badge: "DB",
			color: "#64748b",
			group: "other",
			defaultPort: "",
			hostPlaceholder: "localhost",
		}
	);
}
